import { createAdminClient } from "./supabase/admin";
import { getOrganizationContext, requireOrganizationPermission } from "./organization-context";

const BRANCH_PERMISSION = "branch.manage";
export type Branch = { id:string; organizationId:string; code:string; name:string; address:string|null; contactNo:string|null; email:string|null; status:"ACTIVE"|"INACTIVE"; isDefault:boolean };
async function context(){const c=await getOrganizationContext();if(!c)throw new Error("UNAUTHENTICATED");requireOrganizationPermission(c,BRANCH_PERMISSION);return c;}
export async function listBranches(){const c=await context();const {data,error}=await createAdminClient().from("branches").select("id,organization_id,code,name,address,contact_no,email,status,is_default").eq("organization_id",c.organizationId).order("is_default",{ascending:false}).order("name");if(error)throw new Error(error.message);return (data??[]).map((b:any)=>({id:b.id,organizationId:b.organization_id,code:b.code,name:b.name,address:b.address,contactNo:b.contact_no,email:b.email,status:b.status,isDefault:b.is_default})) as Branch[];}
export async function createBranch(input:Omit<Branch,"id"|"organizationId">){const c=await context();const admin=createAdminClient();if(input.isDefault)await admin.from("branches").update({is_default:false}).eq("organization_id",c.organizationId);const {data,error}=await admin.from("branches").insert({organization_id:c.organizationId,code:input.code.trim().toUpperCase(),name:input.name.trim(),address:input.address||null,contact_no:input.contactNo||null,email:input.email||null,status:input.status||"ACTIVE",is_default:input.isDefault}).select("id,organization_id,code,name,address,contact_no,email,status,is_default").single();if(error)throw new Error(error.message);return data;}
export async function updateBranch(id:string,input:Partial<Omit<Branch,"id"|"organizationId">>){const c=await context();const admin=createAdminClient();const {data:existing}=await admin.from("branches").select("id").eq("id",id).eq("organization_id",c.organizationId).maybeSingle();if(!existing)throw new Error("BRANCH_NOT_FOUND");if(input.isDefault)await admin.from("branches").update({is_default:false}).eq("organization_id",c.organizationId);const patch:any={};if(input.code!==undefined)patch.code=input.code.trim().toUpperCase();if(input.name!==undefined)patch.name=input.name.trim();if(input.address!==undefined)patch.address=input.address||null;if(input.contactNo!==undefined)patch.contact_no=input.contactNo||null;if(input.email!==undefined)patch.email=input.email||null;if(input.status!==undefined)patch.status=input.status;if(input.isDefault!==undefined)patch.is_default=input.isDefault;const {data,error}=await admin.from("branches").update(patch).eq("id",id).eq("organization_id",c.organizationId).select("id,organization_id,code,name,address,contact_no,email,status,is_default").single();if(error)throw new Error(error.message);return data;}
